#!/bin/bash
# Filename: install
# Description: Initialize Git and install user-defined packages
# Reference:
# [1] https://ss64.com/bash/syntax-file-operators.html
# [2] https://ss64.com/bash/syntax-substitution.html
# [15] https://ss64.com/bash/tr.html

################################################################################
# Initiaiization                                                               #
################################################################################

# Set the username
username=$1
# Set the requirement filename
file_path=$2

################################################################################
# Main program                                                                 #
################################################################################

# Step 1: Install dependencies and packages

# Check if requirement exist
# -f checks if requirement is a regular file [1]
if [[ -f $file_path ]]; then
    # Installs packages listed in the 'requirement' file
    # $(cat requirement) will substitue the content of given file [2]
    # tr "\r" " " will replace all end of line to space
    pacman -S --needed --noconfirm  $(cat $file_path | tr "\r" " ")
else
    # Print an error message
    echo You have not create a requirement file
    # Exit the script
    exit 1
fi
