#!/bin/bash
# Filename: setup
# Description: Initialize Git and install user-defined packages
# Reference:
  # [1] https://ss64.com/bash/syntax-file-operators.html
  # [2] https://ss64.com/bash/syntax-substitution.html

# Step 1: Install dependencies and packages
if [[ -f /home/arch/requirement ]];then 
  # Check if requirement exist
  # -f checks if requirement is a regular file [1]
  pacman -S --noconfirm $(cat requirement | tr "\r" " ") 
  # Installs packages listed in the 'requirement' file
  # $(cat requirement) will substitue the content of requirement [2]
else
  echo You have not create a requirement file # Print an error message
  exit 1                                      # Exit the script
fi
