#!/bin/bash
# Filename: install
# Description: Initialize Git and install user-defined packages
# Reference:
# [1] https://ss64.com/bash/syntax-file-operators.html
# [2] https://ss64.com/bash/syntax-substitution.html

################################################################################
# Initiaiization                                                               #
################################################################################

username=$1 # Set the username
filename=$2 # Set the requirement filename

################################################################################
# Main program                                                                 #
################################################################################
# Step 1: Install dependencies and packages

: <<'COMMENT'
Check if requirement exist
-f checks if requirement is a regular file [1]
Installs packages listed in the 'requirement' file
$(cat requirement) will substitue the content of requirement [2]
Print an error message
Exit the script
COMMENT


if [[ -f /home/$username/$filename ]]; then
    pacman -S --noconfirm $(cat /home/$username/$filename | tr "\r" " ")
else
    echo "$filename doesn't exist"
    exit 1
fi