#!/bin/bash
# Filename: setup
# Description: Run setup and link scripts
# Reference: 
# [8] https://ss64.com/bash/ps.html 
# [9] https://ss64.com/bash/sudo.html

################################################################################
# Initiaiization                                                               #
################################################################################
user=$SUDO_USER                          # Set a user variable for username

################################################################################
# Error Handling                                                               #
################################################################################
if [[ $EUID -ne 0 ]];then                # Check if the script is run by root privillege [8]
  echo "You need to 'sudo' this script"  # Print an error message
  exit 1                                 # Exit the script
fi

################################################################################
# Main program                                                                 #
################################################################################
./install $user                          # Run setup script
./link $user                             # Run link script